version: '3'
services:
    app:
        image: marketplace
        container_name: marketplace-container
        build:
            context: .
        restart: on-failure
        volumes:
            - ./:/var/www/html/marketplace
        ports:
            - "5000:${FLASK_RUN_PORT}"
        depends_on:
            - rabbitmq
            - db

    db:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/data/pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - "5435:5432"

    rabbitmq:
        container_name: app-rabbitmq
        image: 'rabbitmq:3.7-management'
        restart: unless-stopped
        ports:
            - 5630:5672
            - 8090:15672
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

    elasticsearch:
        container_name: app-elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    prometheus:
        container_name: app-prometheus
        image: prom/prometheus:v2.36.1
        volumes:
            - ./etc/prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - "9999:9090"

    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        user: "472"
        container_name: app-grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
          - ./etc/grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
        env_file:
          - ./etc/grafana/config.monitoring
