scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'app_marketplace_backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['marketplace-container:5000']
    metrics_path: /metrics
    basic_auth:
      username: 'user'
      password: 'user_password'
