"""empty message

Revision ID: 44d66f6fc574
Revises: d6dd96c90252
Create Date: 2022-10-20 15:28:02.232238

"""
from alembic import op
import sqlalchemy as sa

from src.shared.infrastructure.persistence.sqlalchemy.decorators.outbox_id_decorator import OutboxIdDecorator

# revision identifiers, used by Alembic.
revision = '44d66f6fc574'
down_revision = 'd6dd96c90252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', OutboxIdDecorator(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox')
    # ### end Alembic commands ###
