"""empty message

Revision ID: 52b811ab4ae1
Revises: 
Create Date: 2022-11-01 17:43:47.607242

"""
from alembic import op
import sqlalchemy as sa

from src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.event_id_decorator import EventIdDecorator
from src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.mode_decorator import ModeDecorator
from src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.zone_id_decorator import ZoneIdDecorator
from src.shared.infrastructure.persistence.sqlalchemy.decorators.outbox_id_decorator import OutboxIdDecorator
from src.shared.infrastructure.persistence.sqlalchemy.decorators.price_decorator import PriceDecorator

# revision identifiers, used by Alembic.
revision = '52b811ab4ae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', EventIdDecorator(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('mode', ModeDecorator(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('provider_organizer_company_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('sell_from', sa.DateTime(), nullable=False),
    sa.Column('sell_to', sa.DateTime(), nullable=False),
    sa.Column('sold_out', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_table('outbox',
    sa.Column('id', OutboxIdDecorator(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone',
    sa.Column('id', ZoneIdDecorator(), nullable=False),
    sa.Column('provider_zone_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price', PriceDecorator(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('numbered', sa.Boolean(), nullable=False),
    sa.Column('event_id', EventIdDecorator(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone')
    op.drop_table('outbox')
    op.drop_table('event')
    # ### end Alembic commands ###
