"""Add event file table

Revision ID: bd687f0e65dd
Revises: 5a03270b457b
Create Date: 2023-01-14 17:49:14.153668

"""
from alembic import op
import sqlalchemy as sa

from src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.event_id_decorator import EventIdDecorator
from src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.file_id_decorator import FileIdDecorator

# revision identifiers, used by Alembic.
revision = 'bd687f0e65dd'
down_revision = '5a03270b457b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_file',
        sa.Column('id', FileIdDecorator(), nullable=False),
        sa.Column('file', sa.String(length=200), nullable=False),
        sa.Column('event_id', EventIdDecorator(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_file')
    # ### end Alembic commands ###
