"""empty message

Revision ID: d6dd96c90252
Revises: 
Create Date: 2022-09-14 17:09:02.998513

"""
from alembic import op
import sqlalchemy as sa
import src

# revision identifiers, used by Alembic.
revision = 'd6dd96c90252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.event_id_decorator.EventIdDecorator(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('mode', src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.mode_decorator.ModeDecorator(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('provider_organizer_company_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('sell_from', sa.DateTime(), nullable=False),
    sa.Column('sell_to', sa.DateTime(), nullable=False),
    sa.Column('sold_out', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_table('zone',
    sa.Column('id', src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.zone_id_decorator.ZoneIdDecorator(), nullable=False),
    sa.Column('provider_zone_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price', src.shared.infrastructure.persistence.sqlalchemy.decorators.price_decorator.PriceDecorator(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('numbered', sa.Boolean(), nullable=False),
    sa.Column('event_id', src.marketplace.event.infrastructure.persistence.sqlalchemy.decorators.event_id_decorator.EventIdDecorator(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone')
    op.drop_table('event')
    # ### end Alembic commands ###
