{
 "title": "Marketplace metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Domain events",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(type) as total, MAX(type) as domain_event FROM outbox GROUP BY aggregate_type"
    }
   ]
  },
  {
   "title": "Domain events",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "domain_events_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total requests in a period of time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_count[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request time /events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[24h]) / rate(http_request_duration_seconds_count[24h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}